import type { Metadata } from 'next'
import { Open_Sans } from "next/font/google";

import './globals.css'
import { Header } from '@/components/header';
const font = Open_Sans({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: 'Next-Demo-App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning> 
      <body className={font.className}>
        <Header/>
        {children}</body>
    </html>
  )
}
